Select COD_BALANCE, FECHA, SALDO, COD_ACTIVO, COD_PASIVO, COD_PATRIMONIO, COD_ESTADO_RESULTADO from bancorp.balance_general
USE bancorp;

CREATE TABLE `balance_general` (
  `COD_BALANCE` bigint(20) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `SALDO` int(11) NOT NULL,
  `COD_ACTIVO` bigint(20) DEFAULT NULL,
  `COD_PASIVO` bigint(20) DEFAULT NULL,
  `COD_PATRIMONIO` bigint(20) DEFAULT NULL,
  `COD_ESTADO_RESULTADO` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`COD_BALANCE`),
  KEY `Â´COD_ACTIVOÂ´` (`COD_ACTIVO`),
  KEY `Â´COD_PASIVOÂ´` (`COD_PASIVO`),
  KEY `Â´COD_PATRIMINIOÂ´` (`COD_PATRIMONIO`),
  KEY `Â´COD_ESTADO_RESULTADOÂ´` (`COD_ESTADO_RESULTADO`),
  CONSTRAINT `Â´COD_ACTIVOÂ´` FOREIGN KEY (`COD_ACTIVO`) REFERENCES `activos` (`COD_ACTIVO`) ON DELETE CASCADE,
  CONSTRAINT `Â´COD_ESTADO_RESULTADOÂ´` FOREIGN KEY (`COD_ESTADO_RESULTADO`) REFERENCES `estado_resultado` (`COD_ESTADO_RESULTADO`) ON DELETE CASCADE,
  CONSTRAINT `Â´COD_PASIVOÂ´` FOREIGN KEY (`COD_PASIVO`) REFERENCES `pasivos` (`COD_PASIVO`) ON DELETE CASCADE,
  CONSTRAINT `Â´COD_PATRIMINIOÂ´` FOREIGN KEY (`COD_PATRIMONIO`) REFERENCES `patrimonio` (`COD_PATRIMONIO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


