Select COD_CLIENTE, COD_USUARIO from bancorp.clientes
USE bancorp;

CREATE TABLE `clientes` (
  `COD_CLIENTE` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE CLIENTE',
  `COD_USUARIO` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`COD_CLIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


