Select COD_CORREO, COD_PERSONA, CORREO from bancorp.correos
USE bancorp;

CREATE TABLE `correos` (
  `COD_CORREO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA CORREOS',
  `COD_PERSONA` bigint(20) DEFAULT NULL,
  `CORREO` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'CORREO ELECTRONICO DE LA PERSONA',
  PRIMARY KEY (`COD_CORREO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


