Select COD_CTA, COD_CLIENTE, NUM_CTA, TIP_CTA, FEC_REGISTRO, SAL_CTA, IND_CTA from bancorp.cuentas
USE bancorp;

CREATE TABLE `cuentas` (
  `COD_CTA` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA CUENTA',
  `COD_CLIENTE` bigint(20) DEFAULT NULL,
  `NUM_CTA` bigint(50) NOT NULL COMMENT 'NUMERO DE CUENTA',
  `TIP_CTA` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'TIPO DE CUENTA',
  `FEC_REGISTRO` datetime NOT NULL COMMENT 'FECHA DE REGISTRO DE LA CUENTA ',
  `SAL_CTA` double NOT NULL COMMENT 'SALDO DE LA CUENTA',
  `IND_CTA` enum('1','0') COLLATE utf8_unicode_ci NOT NULL COMMENT 'ESTADO DE LA CUENTA',
  PRIMARY KEY (`COD_CTA`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO bancorp.cuentas(COD_CTA,COD_CLIENTE,NUM_CTA,TIP_CTA,FEC_REGISTRO,SAL_CTA,IND_CTA) VALUES (2,null,4547878,'Ahorro','2022-04-29 00:00:00',187545,'1');
INSERT INTO bancorp.cuentas(COD_CTA,COD_CLIENTE,NUM_CTA,TIP_CTA,FEC_REGISTRO,SAL_CTA,IND_CTA) VALUES (3,null,8011999,'Ahorro','2022-04-29 00:00:00',15000,'1');
