Select COD_EMPLEADO, COD_USUARIO, NOM_EMPLEADO, APE_EMPLEADO, IDENTIDAD, CAR_EMPLEADO, IND_EMPLEADO from bancorp.empleados
USE bancorp;

CREATE TABLE `empleados` (
  `COD_EMPLEADO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DEL EMPLEADO',
  `COD_USUARIO` bigint(20) DEFAULT NULL,
  `NOM_EMPLEADO` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DEL EMPLEADO',
  `APE_EMPLEADO` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'APELLIDO DEL EMPLEADO',
  `IDENTIDAD` int(20) NOT NULL COMMENT 'NUMERO DE IDENTIDAD DEL EMPLEADO',
  `CAR_EMPLEADO` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'CARGO DEL EMPLEADO',
  `IND_EMPLEADO` enum('1','0') COLLATE utf8_unicode_ci NOT NULL COMMENT 'ESTADO DEL EMPLEADO',
  PRIMARY KEY (`COD_EMPLEADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


