Select COD_INFO_EMPRESA, COD_SOLICITUD, NOM_EMPRESA, TIPO_EMPLEADO, CARGO, ANTIGUEDAD from bancorp.info_empresa
USE bancorp;

CREATE TABLE `info_empresa` (
  `COD_INFO_EMPRESA` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE LA TABLA DE INFORMACION DE LA EMPRESA',
  `COD_SOLICITUD` bigint(20) DEFAULT NULL,
  `NOM_EMPRESA` varchar(250) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DE LA EMPRESA DONDE LABORA',
  `TIPO_EMPLEADO` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'TIPO DE EMPLEADO',
  `CARGO` varchar(250) COLLATE utf8_unicode_ci NOT NULL COMMENT 'PUESTO QUE EJERCE',
  `ANTIGUEDAD` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ANTIGUEDAD LABORAL',
  PRIMARY KEY (`COD_INFO_EMPRESA`),
  KEY `FK_INFO_EMPRESA_SOLICITUD` (`COD_SOLICITUD`),
  CONSTRAINT `FK_INFO_EMPRESA_SOLICITUD` FOREIGN KEY (`COD_SOLICITUD`) REFERENCES `solicitud` (`COD_SOLICITUD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


