Select COD_MOVIMIENTO, COD_CTA, FEC_MOVIMIENTO, MON_MOVIMIENTO, TIP_MOVIMIENTO from bancorp.movimientos
USE bancorp;

CREATE TABLE `movimientos` (
  `COD_MOVIMIENTO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'NUMERO DE MOVIMIENTOS',
  `COD_CTA` bigint(20) DEFAULT NULL,
  `FEC_MOVIMIENTO` datetime NOT NULL COMMENT 'FECHA DE MOVIMIENTO',
  `MON_MOVIMIENTO` double NOT NULL COMMENT 'MONTO DE MOVIMIENTO',
  `TIP_MOVIMIENTO` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'TIPO DE MOVIMIENTO',
  PRIMARY KEY (`COD_MOVIMIENTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


