Select COD_PAGO, PAGO_PROGRAMADO, N_PAGOS_PROGRAMADO, PAGO_ANTICIPADO from bancorp.pago
USE bancorp;

CREATE TABLE `pago` (
  `COD_PAGO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE PAGO',
  `PAGO_PROGRAMADO` double NOT NULL COMMENT 'PAGO PROGRAMADO',
  `N_PAGOS_PROGRAMADO` int(20) NOT NULL COMMENT 'NUMERO DE PAGOS PROGRAMADO (12)',
  `PAGO_ANTICIPADO` double NOT NULL COMMENT 'PAGOS ANTICIPADOS',
  PRIMARY KEY (`COD_PAGO`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO bancorp.pago(COD_PAGO,PAGO_PROGRAMADO,N_PAGOS_PROGRAMADO,PAGO_ANTICIPADO) VALUES (21,7000,12,4);
