Select COD_PATRIMONIO, NOM_PATRIMONIO, VALOR_PATRIMONIO, FECHA_PATRIMONIO from bancorp.patrimonio
USE bancorp;

CREATE TABLE `patrimonio` (
  `COD_PATRIMONIO` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOM_PATRIMONIO` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `VALOR_PATRIMONIO` int(11) NOT NULL,
  `FECHA_PATRIMONIO` datetime DEFAULT NULL,
  PRIMARY KEY (`COD_PATRIMONIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


