Select COD_PERSONA, NOM_PERSONA, APE_PERSONA, IDENTIDAD, SEX_PERSONA, IND_CIVIL, EDA_PERSONA, DIR_PERSONA, TIP_PERSONA, IND_PERSONA, USR_REGISTRO, FEC_REGISTRO from bancorp.personas
USE bancorp;

CREATE TABLE `personas` (
  `COD_PERSONA` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA PERSONAS',
  `NOM_PERSONA` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DE LA PERSONA',
  `APE_PERSONA` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'APELLIDO DE LA PERSONA',
  `IDENTIDAD` int(20) NOT NULL COMMENT 'NUMERO DE IDENTIDAD DE LA PERSONA',
  `SEX_PERSONA` enum('F','M') COLLATE utf8_unicode_ci NOT NULL COMMENT 'SEXO DE LA PERSONA',
  `IND_CIVIL` enum('S','C','D','V') COLLATE utf8_unicode_ci NOT NULL COMMENT 'ESTADO CIVIL DE LA PERSONA',
  `EDA_PERSONA` tinyint(4) NOT NULL COMMENT 'EDAD DE LA PERSONA',
  `DIR_PERSONA` varchar(300) COLLATE utf8_unicode_ci NOT NULL COMMENT 'DIRECCION DE LA PERSONA',
  `TIP_PERSONA` enum('N','J') COLLATE utf8_unicode_ci NOT NULL COMMENT 'TIPO DE PERSONA',
  `IND_PERSONA` enum('1','0') COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'ESTADO DE LA PERSONA',
  `USR_REGISTRO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'USUARIO QUE REGISTRA',
  `FEC_REGISTRO` datetime NOT NULL COMMENT 'FECHA DE REGISTRO',
  PRIMARY KEY (`COD_PERSONA`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO bancorp.personas(COD_PERSONA,NOM_PERSONA,APE_PERSONA,IDENTIDAD,SEX_PERSONA,IND_CIVIL,EDA_PERSONA,DIR_PERSONA,TIP_PERSONA,IND_PERSONA,USR_REGISTRO,FEC_REGISTRO) VALUES (2,'Kevin','Lopez',545,'M','C',64,'Quezada','J','1','miri123','2022-04-29 00:00:00');
