Select COD_PRESTAMO, IMPORTE_PRESTAMO, INTERESES, PLAZO_ANUAL, N_PAGOSANUAL, SALDO_FINAL, FECHA_PRESTAMO, NOMBRE, APELLIDO from bancorp.prestamo
USE bancorp;

CREATE TABLE `prestamo` (
  `COD_PRESTAMO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE PRESTAMO',
  `IMPORTE_PRESTAMO` double NOT NULL COMMENT 'PRESTAMO SOLICITADO',
  `INTERESES` double NOT NULL COMMENT '4% DE INTERESES',
  `PLAZO_ANUAL` int(20) NOT NULL COMMENT 'PRESTAMO POR AÃƒâ€˜OS',
  `N_PAGOSANUAL` int(20) NOT NULL COMMENT 'NUMERO DE PAGOS ANUAL',
  `SALDO_FINAL` double NOT NULL COMMENT 'SALDO FINAL DEL PRESTAMO',
  `FECHA_PRESTAMO` date NOT NULL COMMENT 'FECHA INICIO DE PRESTAMO',
  `NOMBRE` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `APELLIDO` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`COD_PRESTAMO`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO bancorp.prestamo(COD_PRESTAMO,IMPORTE_PRESTAMO,INTERESES,PLAZO_ANUAL,N_PAGOSANUAL,SALDO_FINAL,FECHA_PRESTAMO,NOMBRE,APELLIDO) VALUES (19,17000,0.03,1,12,17000,'2022-04-28 00:00:00','Michael','Sosa');
INSERT INTO bancorp.prestamo(COD_PRESTAMO,IMPORTE_PRESTAMO,INTERESES,PLAZO_ANUAL,N_PAGOSANUAL,SALDO_FINAL,FECHA_PRESTAMO,NOMBRE,APELLIDO) VALUES (20,18000,0.04,1,12,18000,'2022-04-28 00:00:00','Allan','Salinas');
INSERT INTO bancorp.prestamo(COD_PRESTAMO,IMPORTE_PRESTAMO,INTERESES,PLAZO_ANUAL,N_PAGOSANUAL,SALDO_FINAL,FECHA_PRESTAMO,NOMBRE,APELLIDO) VALUES (24,100,0.04,2,24,100,'2022-04-28 00:00:00','Cristiano','Ronaldo');
