Select ID_REPORTE, COD_CTA, COD_USUARIO, CLAVE, NUM_CTA, TIP_CTA, FEC_REGISTRO, SAL_CTA, IND_CTA from bancorp.reportes
USE bancorp;

CREATE TABLE `reportes` (
  `ID_REPORTE` bigint(20) NOT NULL AUTO_INCREMENT,
  `COD_CTA` bigint(20) DEFAULT NULL,
  `COD_USUARIO` bigint(20) DEFAULT NULL,
  `CLAVE` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'CLAVE DEL USUARIO',
  `NUM_CTA` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NUMERO DE CUENTA',
  `TIP_CTA` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'TIPO DE CUENTA',
  `FEC_REGISTRO` datetime NOT NULL COMMENT 'FECHA DE REGISTRO DE LA CUENTA ',
  `SAL_CTA` double NOT NULL COMMENT 'SALDO DE LA CUENTA',
  `IND_CTA` enum('1','0') COLLATE utf8_unicode_ci NOT NULL COMMENT 'ESTADO DE LA CUENTA',
  PRIMARY KEY (`ID_REPORTE`),
  KEY `Â´CUENTASÂ´` (`COD_CTA`),
  KEY `Â´USUARIOSÂ´` (`COD_USUARIO`),
  CONSTRAINT `Â´CUENTASÂ´` FOREIGN KEY (`COD_CTA`) REFERENCES `cuentas` (`COD_CTA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `Â´USUARIOSÂ´` FOREIGN KEY (`COD_USUARIO`) REFERENCES `usuarios` (`COD_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO bancorp.reportes(ID_REPORTE,COD_CTA,COD_USUARIO,CLAVE,NUM_CTA,TIP_CTA,FEC_REGISTRO,SAL_CTA,IND_CTA) VALUES (4,null,null,'Diosesamor','805454','UNAH','2022-04-29 02:20:14',1000,'1');
INSERT INTO bancorp.reportes(ID_REPORTE,COD_CTA,COD_USUARIO,CLAVE,NUM_CTA,TIP_CTA,FEC_REGISTRO,SAL_CTA,IND_CTA) VALUES (5,null,null,'HolaM','988745','Unica','2022-04-29 03:06:11',15000,'1');
INSERT INTO bancorp.reportes(ID_REPORTE,COD_CTA,COD_USUARIO,CLAVE,NUM_CTA,TIP_CTA,FEC_REGISTRO,SAL_CTA,IND_CTA) VALUES (6,null,null,'MichaelS1','801199','Unica','2022-04-29 03:06:37',4000,'1');
INSERT INTO bancorp.reportes(ID_REPORTE,COD_CTA,COD_USUARIO,CLAVE,NUM_CTA,TIP_CTA,FEC_REGISTRO,SAL_CTA,IND_CTA) VALUES (7,null,null,'Angel123','819199','Unica','2022-04-29 03:06:58',6000,'1');
INSERT INTO bancorp.reportes(ID_REPORTE,COD_CTA,COD_USUARIO,CLAVE,NUM_CTA,TIP_CTA,FEC_REGISTRO,SAL_CTA,IND_CTA) VALUES (8,null,null,'Gissel','1007223','Unica','2022-04-29 03:13:39',15000,'');
INSERT INTO bancorp.reportes(ID_REPORTE,COD_CTA,COD_USUARIO,CLAVE,NUM_CTA,TIP_CTA,FEC_REGISTRO,SAL_CTA,IND_CTA) VALUES (9,null,null,'Rony ','762518','Mancomunada','2022-04-29 03:14:30',23000,'1');
INSERT INTO bancorp.reportes(ID_REPORTE,COD_CTA,COD_USUARIO,CLAVE,NUM_CTA,TIP_CTA,FEC_REGISTRO,SAL_CTA,IND_CTA) VALUES (10,null,null,'Oscar  ','872910','Mancomunada','2022-04-29 03:15:13',30000,'1');
