Select COD_SOLICITUD, COD_PERSONA, TAR_SOLICITUD, ESTADO_SOLICITUD from bancorp.solicitud
USE bancorp;

CREATE TABLE `solicitud` (
  `COD_SOLICITUD` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE LA TABLA SOLICITUD',
  `COD_PERSONA` bigint(20) DEFAULT NULL,
  `TAR_SOLICITUD` varchar(250) COLLATE utf8_unicode_ci NOT NULL COMMENT 'TIPO DE TARJETA A SOLICITAR',
  `ESTADO_SOLICITUD` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ESTADO DE LA SOLICITUD',
  PRIMARY KEY (`COD_SOLICITUD`),
  KEY `FK_SOLICITUD_PERSONAS` (`COD_PERSONA`),
  CONSTRAINT `FK_SOLICITUD_PERSONAS` FOREIGN KEY (`COD_PERSONA`) REFERENCES `personas` (`COD_PERSONA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


