Select COD_TELEFONO, COD_PERSONA, NUM_TELEFONO, TIP_TELEFONO, USR_REGISTRO, FEC_REGISTRO from bancorp.telefonos
USE bancorp;

CREATE TABLE `telefonos` (
  `COD_TELEFONO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA TELEFONOS',
  `COD_PERSONA` bigint(20) DEFAULT NULL,
  `NUM_TELEFONO` int(10) NOT NULL COMMENT 'NUMERO DE TELEFONO',
  `TIP_TELEFONO` enum('P','C','T') COLLATE utf8_unicode_ci NOT NULL COMMENT ' TIPO DE TELEFONO',
  `USR_REGISTRO` bigint(20) DEFAULT NULL,
  `FEC_REGISTRO` datetime NOT NULL COMMENT 'FECHA QUE REGISTRO',
  PRIMARY KEY (`COD_TELEFONO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


