Select COD_USUARIO, COD_PERSONA, USR_REGISTRO, CLAVE from bancorp.usuarios
USE bancorp;

CREATE TABLE `usuarios` (
  `COD_USUARIO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DEL USUARIO',
  `COD_PERSONA` bigint(20) DEFAULT NULL,
  `USR_REGISTRO` bigint(20) DEFAULT NULL,
  `CLAVE` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'CLAVE DEL USUARIO',
  PRIMARY KEY (`COD_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


